# SMB CSI StorageClass (driver configured via helm chart)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: smb.csi.k8s.io
parameters:
  source: "//SMB_SERVER/SHARE" #patched via kustomize

  # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  # with PV name under source
  csi.storage.k8s.io/provisioner-secret-name: "smb-secret"
  csi.storage.k8s.io/provisioner-secret-namespace: "smb-csi-provisioner"
  csi.storage.k8s.io/node-stage-secret-name: "smb-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "smb-csi-provisioner"
reclaimPolicy: Retain  # available values: Delete, Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000