apiVersion: v1
kind: Namespace
metadata:
  name: go-counter
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-counter-backend
  namespace: go-counter
spec:
  selector:
    matchLabels:
      app: go-counter-backend 
  template:
    metadata:
      labels:
        app: go-counter-backend
    spec:
      nodeSelector:
        type: agent
      containers:
      - name: redis
        image: redis:alpine
        command: ["/bin/sh", "-c"]
        args:
          - redis-server --requirepass "$${REDIS_PASS:?REDIS_PASS not set}" --save 60 1
        envFrom:
        - secretRef:
            name: go-counter-backend-redis-env
        volumeMounts:
        - name: go-counter-backend-redis-pvc
          mountPath: /data
        ports:
        - containerPort: 6379
      - name: counter-consumer
        image: jhawk7/go-counter-consumer:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: go-counter-consumer-env
        - secretRef:
            name: go-counter-backend-redis-env
        - secretRef:
            name: go-counter-backend-mqtt-env
        ports:
        - containerPort: 8889
      - name: counter-producer
        image: jhawk7/go-counter-producer:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: go-counter-producer-env
        - secretRef:
            name: go-counter-backend-redis-env
        - secretRef:
            name: go-counter-backend-mqtt-env
        ports:
        - containerPort: 8888
  volumeClaimTemplates:
  - metadata:
      name: go-counter-backend-redis-pvc
      namespace: go-counter
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "smb"
      resources:
        requests:
          storage: 100Mi