apiVersion: v1
kind: Service
metadata:
  name: go-counter-producer-service
  namespace: go-counter
spec:
  selector:
    app: go-counter-backend
  type: LoadBalancer
  loadBalancerIP: LB_IP #patched via kustomize
  ports:
  - name: http
    port: 8888
    targetPort: 8888
    protocol: TCP