---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dotnetapi
  namespace: apps
  labels:
    app: dotnetapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetapi
  strategy:
    canary: {}
  template:
    metadata:
      labels:
        app: dotnetapi
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: dotnetapi
        image: jhawk7/dotnetapi@sha256:6a31196ce6013d96ad8a0aa16483da40263b00e0048840de8d506872c4c83856
        ports:
        - containerPort: 5256
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5256
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5256
          initialDelaySeconds: 5
          periodSeconds: 5
