apiVersion: v1
kind: Service
metadata:
  name: dotnetapi
  namespace: apps
  labels:
    app: dotnetapi
spec:
  type: LoadBalancer
  selector:
    app: dotnetapi
  ports:
  - port: 5256
    targetPort: 5256
    protocol: TCP
    name: http